on: [push, pull_request]

name: ci

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install vim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: false

      - name: install neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true

      - name: install linter
        run: pip install vim-vint==0.3.21

      - name: lint
        run: make lint

      - name: test-vim
        run: make test-vim

      - name: test-nvim
        run: make test-nvim

  compatibility:
    name: compatibility (${{ matrix.editor }} ${{ matrix.version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - editor: Vim
            version: v8.2.3995
            neovim: false
            target: test-vim
          - editor: Neovim
            version: v0.6.1
            neovim: true
            target: test-nvim

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: install ${{ matrix.editor }} ${{ matrix.version }}
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: ${{ matrix.neovim }}
          version: ${{ matrix.version }}

      - name: test ${{ matrix.editor }} ${{ matrix.version }}
        run: make ${{ matrix.target }}
