on: [push, pull_request]

name: ci

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: install
        run: make install

      - name: lint
        run: make lint

      - name: test-vim
        run: make test-vim

      - name: install neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true

      - name: test-nvim
        run: make test-nvim
